# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculates the local variance with physical boundary conditions
#'
#' @param inWin Window
#' @param inShell Shell of window
#' @param insDiv field of which the local variance should be calculated
#' @param inDims Integer vector of dimensions for input, should be <xDim, yDim, winDim, shellDim>
#'
#' @return Vector with the local variance
#' @export
calculateLocVar_physical <- function(inWin, inShell, insDiv, inDims) {
    .Call('_codeSimData_calculateLocVar_physical', PACKAGE = 'codeSimData', inWin, inShell, insDiv, inDims)
}

#' Calculates the local variance with periodic boundary conditions
#'
#' @param inWin Window
#' @param inShell Shell of window
#' @param insDiv field of which the local variance should be calculated
#' @param inDims Integer vector of dimensions for input, should be <xDim, yDim, winDim, shellDim>
#'
#' @return Vector with the local variance
#' @export
calculateLocVar_periodic <- function(inWin, inShell, insDiv, inDims) {
    .Call('_codeSimData_calculateLocVar_periodic', PACKAGE = 'codeSimData', inWin, inShell, insDiv, inDims)
}

